  - name: Set up Python
    uses: actions/setup-python@v4
    with:
      python-level: '3.10'

  - name: Install Dependencies
    run: |
      sudo apt-get update
      sudo apt-get install -y ffmpeg
      pip install -r requirements.txt

  - name: Run Recorder & Send to Telegram
    env:
      TG_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
      TG_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
    run: |
      # هنا يتم تشغيل الأداة لفحص الأسماء المكتوبة في ملف users.txt
      python main.py -mode automatic -ffmpeg
      
      # كود برمي لإرسال أي فيديو تم تسجيله إلى تليجرام تلقائياً
      for f in *.mp4; do
        [ -e "$f" ] || continue
        curl -F video="@$f" https://telegram.org
      done
